<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Answer;
use AppBundle\Entity\Quiz;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends EntityRepository
{
    /**
     * Get user answers.
     *
     * @param Question $questions
     * @param User $user
     * @return Answer[]
     */
    public function getUserAnswers($questions, User $user)
    {
        $query = $this->_em->createQuery('
            SELECT answer
            FROM AppBundle:Answer answer
            WHERE answer.question in (:questions)
            AND answer.user = :user
        ')
            ->setParameter('questions', $questions)
            ->setParameter('user', $user);

        $result = $query->getResult();
        return $result;
    }

    /**
     * Get quiz answers.
     *
     * @param Quiz $quiz
     * @param User $user
     * @return Answer[]
     */
    public function getQuizAnswers($quiz, User $user)
    {
        $query = $this->_em->createQuery('
            SELECT answer
            FROM AppBundle:Answer answer
            WHERE answer.question in (:quiz.questions)
            AND answer.user = :user
        ')
            ->setParameter('quiz', $quiz)
            ->setParameter('user', $user);

        $result = $query->getResult();
        return $result;
    }
}
