<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends EntityRepository
{
    public function getUserAnswers($questions, User $user)
    {
        $query = $this->_em->createQuery('
            SELECT answer
            FROM AppBundle:Answer answer
            WHERE answer.question in (:questions)
            AND answer.user = :user
        ')
            ->setParameter('questions', $questions)
            ->setParameter('user', $user);

        $result = $query->getResult();
        return $result;
    }
}
