<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Answer;
use AppBundle\Entity\Quiz;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends EntityRepository
{
    public function getNewQuizzes(User $user)
    {
        $qb = $this->_em->createQuery('
            SELECT DISTINCT  a
            FROM AppBundle:Answer a
        ');

        $answers = $qb->getResult();

        $quizzes = array();
        $quizzesAnswers = array();

        /** @var Answer $answer */
        foreach($answers as $answer)
        {
            $quiz = $answer->getQuestion()->getQuiz();
            if($answer->getUser()->getId() == $user->getId() && !in_array($quiz->getId(), $quizzesAnswers))
            {
                array_push($quizzesAnswers, $quiz->getId());
            }
        }

        /** @var Answer $answer */
        foreach($answers as $answer)
        {
            $quiz = $answer->getQuestion()->getQuiz();
            if(!in_array($quiz->getId(), $quizzesAnswers) && !in_array($quiz, $quizzes))
            {
                array_push($quizzes, $quiz);
            }
        }

        return $quizzes;
    }

    public function getUserQuizzes(User $user)
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('DISTINCT IDENTITY(qst.quiz)')
            ->from('AppBundle:Answer', 'asw')

            ->innerJoin('asw.question', 'qst')
            ->where('asw.user = :user')
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }

    public function test(User $user)
    {
        $qb = $this->createQueryBuilder('quiz')
            ->select('q')
            ->from('AppBundle:Quiz', 'q')
            ->where('answer.user != :user')
            ->leftJoin('quiz.questions', 'question')
            ->leftJoin('question.answers', 'answer')
            ;

        return $qb->getQuery()->execute();
    }

    public function findAllRecent($pageNumber, $search, $maxResults = 8)
    {
        $qb = $this->createQueryBuilder('quiz')
            ->select('quiz')
            ->orderBy('quiz.validationDate', 'ASC')
            ->setFirstResult($pageNumber * $maxResults)
            ->setMaxResults($maxResults);

        if (null !== $search && "" != $search) {
            $qb->where('quiz.title LIKE :search')
                ->setParameter('search', '%' . $search . '%');
        }

        return new Paginator($qb);
    }

    public function getFinishedQuiz(User $user)
    {
        $query = $this->_em->createQuery('
            SELECT q
            FROM AppBundle:Quiz
            WHERE q.questions
        ');

        $result = $query->getResult();
        return $result;
    }
}
