<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends EntityRepository
{
    public function getNewQuizzes(User $user)
    {
        $qb = $this->_em->createQuery('
            SELECT q
            FROM AppBundle:Answer answer
            JOIN answer.question q
        ');

        //$qb->setParameter('user', $user);

        return $qb->getResult();
    }

    public function getInProgressQuizzes(User $user)
    {
        $qb = $this->_em->createQuery('
            SELECT answer.question.quiz FROM AppBundle:Answer
            WHERE 
              (SELECT COUNT(question) FROM AppBundle:Question
                WHERE question = answer.question
                AND answer.user = :user) < COUNT(answer.question.quiz.questions)
            ')

            ->setParameter('user', $user);

        return $qb->getResult();
    }

    public function getCompletedQuizzes(User $user)
    {

    }
}
